#! env zsh

alias gs="git status"
alias gl="git log"
alias glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias gsh="git show"
alias ga="git add"
alias gc="git commit"
alias gca="git commit --amend --no-edit"
alias gps="git push"
alias gpl="git pull"
alias gf="git fetch"
alias gd="git diff"
alias gcl="git clone"
alias gch="git checkout"
alias gchr="git checkout --"
alias gb="git branch"
alias gr="git reset"
alias gst="git stash"
alias gstp="git stash pop"
alias gsta="git stash apply"
alias gsts="git stash show"
alias grb="git rebase"
alias gri="git rebase -i"
alias grc="git rebase --continue"
alias grs="git rebase --skip"
alias gra="git rebase --abort"
alias gcp="git cherry-pick"
alias wip="git add . && git commit -m \"WIP\" --no-verify"
alias unwip="git reset HEAD^"