#! env zsh

alias d="docker"
alias dps="docker push"
alias dpl="docker pull"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dr="docker run"
alias ds="docker stop"
alias dk="docker kill"
alias drm="docker rm"
alias dcp="docker container prune"
alias dils="docker image ls"
alias dirm="docker rmi"
alias dip="docker image prune"
alias dcom="docker-compose"